config/routes.rb
BillUp::Application.routes.draw do
  match "account_settings", to: "users#edit", as: "account_settings"
  match "exception_test", to: "welcome#exception_test", as: "exception_test"
  match "pricing", to: "welcome#pricing", as: "pricing"
  match "sign_in", to: "sessions#new", as: "sign_in"
  match "sign_out", to: "sessions#destroy", as: "sign_out"
  match "sign_up", to: "users#new", as: "sign_up"
  match "terms", to: "welcome#terms", as: "terms"
  match "tour", to: "welcome#tour", as: "tour"




  resources :organisations
  resources :sessions
  resources :users




  constraints subdomain: /.+/ do
    resources :clients
    resources :invoices do
      collection do
        get :paid
        get :unpaid
      end
    end
    resources :receipts
    root to: "organisations#show"
  end




  root to: "welcome#index"
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  default_scope order("invoice_number DESC")
  
  scope :paid, where("paid_at is not null")
  scope :unpaid, where(paid_at: nil)
  
  has_paper_trail

  belongs_to :organisation
  belongs_to :client

  validates :description, presence: true
  validates :from, presence: { if: :without_from_address_id? }
  validates :from_address, presence: { if: :without_from_address_id? }
  validates :invoice_number, presence: true, uniqueness: { scope: [:organisation_id] }, numericality: { greater_than: 0 }
  validates :state, presence: true
  validates :to, presence: { if: :without_to_address_id? }
  validates :to_address, presence: { if: :without_to_address_id? }
  validates :uuid, presence: true, uniqueness: true

  validates :from_address_id, presence: { if: :without_from_fields? }, on: :create
  validates :to_address_id, presence: { if: :without_to_fields? }, on: :create

  has_many :line_items, dependent: :destroy

  accepts_nested_attributes_for :line_items, allow_destroy: true

  attr_accessor :from_address_id
  attr_accessor :to_address_id

  # TODO - Implement this as a custom validation
  #before_save :due_date_is_not_before_invoice_date, message: "due date must be after invoice date."
  before_create :fill_in_addresses




  STATES = {
    I18n.t("models.invoices.states.invoice") => "invoice",
    I18n.t("models.invoices.states.quote")   => "quote",
  }





  def self.random_state
    STATES[STATES.to_a[rand STATES.size].first]
  end
  
  def line_item_units
    line_items.group_by { |u| u.currency }
  end

  def totals
    totals = {}
    self.line_item_units.each do |currency, line_items|
      unit_total = 0.0
      for line_item in line_items do
        unit_total = unit_total + line_item.total
      end
      totals[currency] = unit_total
    end
    totals
  end

  def file_name
    "#{I18n.t("views.invoices.show.copy.states.#{self.state}")} #{self.invoice_number} #{I18n.t("views.invoices.show.labels.to")} #{self.client.name}.pdf"
  end
  
  def paid?
    self.paid_at.present?
  end

  def unpaid?
    self.paid_at.blank?
  end
  
  def past_due?
    self.unpaid? && (Time.now > self.due_at)
  end

private

  #def due_date_is_not_before_invoice_date
  #  self.due_at >= self.invoiced_at
  #end

  def fill_in_addresses
    to_address = Address.find_by_id(self.to_address_id)
    from_address = Address.find_by_id(self.from_address_id)

    self.from = from_address.addressable.name
    self.from_address = from_address.formatted_address

    self.to = to_address.addressable.name
    self.to_address = to_address.formatted_address
  end

  def without_from_address_id?
    self.from_address_id.blank?
  end

  def without_to_address_id?
    self.to_address_id.blank?
  end
  
  def without_from_fields?
    self.from_address.blank? || self.from.blank?
  end

  def without_to_fields?
    self.to_address.blank? || self.to.blank?
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :sign_in_required
  before_filter :current_organisation
  before_filter :membership_required

  load_and_authorize_resource

  def paid
    @invoices = @current_organisation.invoices.paid
  end

  def unpaid
    @invoices = @current_organisation.invoices.unpaid
  end

  def index
    @invoices = @current_organisation.invoices
  end

  def show
    @invoice = @current_organisation.invoices.find_by_id(params[:id])
  end

  def new
    @client = @current_organisation.clients.find_by_id(params[:client_id]) if params[:client_id]
    if @client.present?
      @client_addresses = @client.addresses
    else
      # Finds all addresses associated to all the clients of this organisation:
      # Ref: http://stackoverflow.com/questions/7211846/rails-nested-has-many-association-finding-all-children
      @client_addresses = @current_organisation.clients.map(&:addresses).flatten
    end

    @invoice = Invoice.new
    @invoice.due_at = Time.now + @current_organisation.preferred_due_in_period.days
    @invoice.from = @current_organisation.name
    @invoice.from_address = @current_organisation.current_address
    @invoice.uuid = SecureRandom.uuid
    @invoice.line_items.build
    @invoice.terms = @current_organisation.preferred_terms
    @invoice.notes = @current_organisation.preferred_notes

    if @current_organisation.invoices.blank?
      @invoice.invoice_number = 1
    else
      @invoice.invoice_number = @current_organisation.invoices.first.invoice_number + 1
    end
  end

  def create
    @invoice = Invoice.new(params[:invoice])
    @invoice.organisation = @current_organisation
    @invoice.client = Address.find_by_id(params[:invoice][:to_address_id]).addressable if params[:invoice][:to_address_id].present?

    if @invoice.save
      flash[:success] = t('controllers.invoices_controller.actions.create.success', :state => @invoice.state)
      redirect_to @invoice
    else
      # Reset @client_addresses so that validation errors can be presented correctly
      if @client.present?
        @client_addresses = @client.addresses
      else
        # Finds all addresses associated to all the clients of this organisation:
        # Ref: http://stackoverflow.com/questions/7211846/rails-nested-has-many-association-finding-all-children
        @client_addresses = @current_organisation.clients.map(&:addresses).flatten
      end
      render :action => "new"
    end
  end

  def edit
    @invoice = @current_organisation.invoices.find_by_id(params[:id])
  end

  def update
    @invoice = @current_organisation.invoices.find_by_id(params[:id])

    if @invoice.update_attributes(params[:invoice])
      flash[:success] = t('controllers.invoices_controller.actions.update.success', :state => @invoice.state)
      redirect_to @invoice
    else
      render action: "edit"
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_actions.html.erb
<% if !edit_or_update_action? %>
	<div class="actions">
		<p>
			<small>
			<%= link_to_unless_current t("views.invoices._actions.links.view"), invoice_path(invoice) %>
			| <%= link_to_unless_current t("views.invoices._actions.links.pdf"), invoice_path(invoice, format: "pdf") %>
			| <%= link_to_unless_current t("views.invoices._actions.links.edit"), edit_invoice_path(invoice) %>
			<% if invoice.paid_at.blank? %>
			<br />
			<%= link_to_unless_current t("views.invoices._actions.links.acknowledge"), "#" %>
			| <%= link_to_unless_current t("views.invoices._actions.links.reconcile"), "#" %>
			<% end %>
			</small>
		</p>
	</div>
<% else %>
	<div class="actions">
		<p>
			<small>
			<%= link_to_unless_current t("views.invoices.clickables.links.cancel"), invoice %>
		</p>
	</div>
<% end %>

app/views/invoices/_errors.html.erb
<% if invoice.errors.any? %>
	<div id="error_explanation" class="alert-message block-message error">
	  <a class="close" data-dismiss="alert" href="#">&times;</a>

	  <h2><%= t("views.invoices._errors.title") %></h2>

    <ul>
    <% invoice.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/invoices/_form.html.erb
<%= nested_form_for(@invoice) do |f| %>
	<fieldset class="control-group">

		<%= render "errors", invoice: @invoice %>

		<div class="row">
			<div class="span4">
				<fieldset class="control-group">
					<legend><%= t("views.invoices._form.legends.state") %></legend>
					<%= f.label :state, t("views.invoices._form.labels.state") %>
					<div class="controls">
						<%= f.select :state, Invoice::STATES %>
					</div>
				</fieldset>
			</div>

			<div class="span4">
				<fieldset class="control-group">
					<legend><%= t("views.invoices._form.legends.invoice_number") %></legend>
					<%= f.label :invoice_number, t("views.invoices._form.labels.invoice_number") %>
			    <div class="controls"><%= f.text_field :invoice_number, class: "span3", readonly: true %></div>
				</fieldset>
			</div>

			<div class="span4">
				<fieldset class="control-group">
					<legend><%= t("views.invoices._form.legends.uuid") %></legend>
					<%= f.label :uuid, t("views.invoices._form.labels.uuid") %>
			    <div class="controls"><%= f.text_field :uuid, class: "span3", readonly: true %></div>
				</fieldset>
			</div>
		</div>

		<% if new_or_create_action? %>
			<%= render 'form_fields_for_new', { invoice: @invoice, client_addresses: @client_addresses, client: @client , current_organisation: @current_organisation, f: f } %>
		<% else %>
			<%= render 'form_fields_for_edit', { invoice: @invoice, f: f} %>
		<% end %>

		<div class="row">
			<div class="span6">
				<fieldset class="control-group">
					<legend><%= t("views.invoices._form.legends.description") %></legend>
					<%= f.label :description, t("views.invoices._form.labels.description") %>
			    <div class="controls"><%= f.text_area :description, class: "span5", rows: 7 %></div>
				</fieldset>
			</div>
			<div class="span6">
				<fieldset class="control-group">
					<legend><%= t("views.invoices._form.legends.dates") %></legend>
					<div class="row">
						<div class="span2">
							<fieldset>
								<%= f.label :invoiced_at, t("views.invoices._form.labels.invoiced_at") %>
							  <div class="controls"><%= f.date_select :invoiced_at, {}, class: "span2" %></div>
							</fieldset>
						</div>
						<div class="span2">
							<fieldset>
								<%= f.label :due_at, t("views.invoices._form.labels.due_at") %>
							  <div class="controls"><%= f.date_select :due_at, {}, class: "span2" %></div>
							</fieldset>
						</div>
						<div class="span2">
							<fieldset>
								<%= f.label :paid_at, t("views.invoices._form.labels.paid_at") %>
							  <div class="controls"><%= f.date_select :paid_at, { prompt: true }, class: "span2" %></div>
							</fieldset>
						</div>
					</div><!-- /.row -->
				</fieldset>				
			</div>
		</div>
		
		<!-- Line Items -->
		<fieldset id="line_items" class="control-group">
			<legend><%= t("views.invoices._form.legends.line_items") %></legend>
			<%= f.fields_for :line_items do |builder| %>
				<%= render "line_item_fields", f: builder %>
			<% end %>
			<p><small><%= f.link_to_add t("views.invoices._form.links.add_a_line_item"), :line_items %></small></p>
		</fieldset>
		<!-- /Line Items -->

		<div class="row">
			<div class="span6">
				<fieldset class="control-group">
					<legend><%= t("views.invoices._form.legends.terms") %></legend>
					<%= f.label :terms, t("views.invoices._form.labels.terms") %>
			    <div class="controls"><%= f.text_area :terms, class: "span5", rows: 5 %></div>
				</fieldset>
			</div>
			<div class="span6">
				<fieldset class="control-group">
					<legend><%= t("views.invoices._form.legends.notes") %></legend>
					<%= f.label :notes, t("views.invoices._form.labels.notes") %>
			    <div class="controls"><%= f.text_area :notes, class: "span5", rows: 5 %></div>
				</fieldset>
			</div>
		</div>

	  <div class="actions form-actions">
	    <%= f.submit class: "btn btn-large btn-primary" %>
	  </div>
	</fieldset>
<% end %>

app/views/invoices/_form_fields_for_edit.html.erb
<div class="row">
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.invoices._form.legends.to") %></legend>

			<fieldset class="control-group">
				<%= f.label :to, t("views.invoices._form.labels.to") %>
		    <div class="controls"><%= f.text_field :to, class: "span3" %></div>
			</fieldset>

			<fieldset class="control-group">
				<%= f.label :to_address, raw(t("views.invoices._form.labels.to_address")) %>
		    <div class="controls"><%= f.text_area :to_address, class: "span5", rows: 7 %></div>
			</fieldset>
		</fieldset>
	</div>
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.invoices._form.legends.from") %></legend>

			<fieldset class="control-group">
				<%= f.label :from, t("views.invoices._form.labels.from") %>
		    <div class="controls"><%= f.text_field :from, class: "span3" %></div>
			</fieldset>

			<fieldset class="control-group">
				<%= f.label :from_address, raw(t("views.invoices._form.labels.from_address")) %>
		    <div class="controls"><%= f.text_area :from_address, class: "span5", rows: 7 %></div>
			</fieldset>
		</fieldset>
	</div>
</div>

app/views/invoices/_form_fields_for_new.html.erb
<div class="row">
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.invoices._form.legends.to") %></legend> <%= f.label :to_address_id, t("views.invoices._form.labels.to") %>
			<div class="controls">
				<%= f.collection_select(:to_address_id, client_addresses, :id, :summary, { prompt: true }, { class: "span5" }) %>
				<% if client.present? %>
					<p class="help-block">
						<%=raw t("views.invoices._form.copy.hints.to_address_id", client_name: client.name) %>
						<small><%= link_to t("views.invoices.clickables.links.all_clients"), new_invoice_path %><%= t("views.application.copy.full_stop") %></small>
					</p>
				<% end %>
			</div>
		</fieldset>
	</div>
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.invoices._form.legends.from") %></legend> <%= f.label :from_address_id, t("views.invoices._form.labels.from") %>
			<div class="controls">
				<%= f.collection_select(:from_address_id, current_organisation.addresses, :id, :summary, {}, { class: "span5" }) %>
			</div>
		</fieldset>
	</div>
</div>

app/views/invoices/_invoices.html.erb
<% if invoices.present? %>
	<%= render "tablesorter", { table: "table_of_invoices", column_number: 3 } %>
	<div id="invoices_table">
		<table id="table_of_invoices" class="table table-condensed table table-striped">
		  <thead>
				<tr>
				  <th class="invoice_number"><%= t("views.invoices._invoices.copy.table_headings.invoice_number") %></th>
				  <th class="to"><%= t("views.invoices._invoices.copy.table_headings.to") %></th>
				  <th class="total"><%= t("views.invoices._invoices.copy.table_headings.total") %></th>
				  <th class="invoiced_at"><%= t("views.invoices._invoices.copy.table_headings.invoiced_at") %></th>
				  <th class="due_at"><%= t("views.invoices._invoices.copy.table_headings.due_at") %></th>
					<th class="buttons_and_links"><%= t("views.invoices._invoices.copy.table_headings.actions") %></th>
				</tr>
			</thead>
		  <tbody>
				<% invoices.each do |invoice| %>
			  <tr class="invoice">
			    <td class="invoice_number">
						<%= link_to_unless_current invoice.invoice_number, invoice, { rel: "tooltip", title: "#{invoice.client.name}#{t("views.application.copy.full_colon")} #{invoice.description}" } %>
					</td>
			    <td class="to"><%= link_to_unless_current invoice.to, invoice.client %></td>
			    <td class="total">
						<% totals = [] %>
						<% invoice.totals.each do |currency, total| %>
							<% totals << "#{t("models.currency.codes.#{currency}")}#{number_to_currency(total, :unit => "")}" %>
						<% end %>
						<%= totals.join(", ") %>
					</td>
			    <td class="invoiced_at" title="<%= invoice.invoiced_at.strftime("%A, %d %B %Y") %>">
						<%= invoice.invoiced_at.strftime("%Y-%m-%d") %>
					</td>
			    <td class="due_at" title="<%= "#{t("views.invoices._invoices.copy.due")}#{t("views.application.copy.full_colon")} #{invoice.due_at.strftime("%A, %d %B %Y")}" %>">
						<%= invoice.due_at.strftime("%Y-%m-%d") %>
						<%= render "invoices/invoice_payment_status", invoice: invoice %>
					</td>
			    <td class="buttons_and_links">
						<%= render "invoices/buttons_and_links", invoice: invoice %>
					</td>
			  </tr>
				<% end %>
			</tbody>
		</table>
	</div><!-- /#invoices_table -->
<% else %>
	<%= render "invoices/no_invoices"%>
<% end %>

app/views/invoices/_line_item_fields.html.erb
<div class="row">
	<div class="span1">
		<fieldset class="control-group">
			<%= f.label :quantity, t("views.invoices._form.labels.quantity"), class: "control-label" %>
	    <div class="controls"><%= f.text_field :quantity, class: "span1" %></div>
		</fieldset>
	</div>

	<div class="span4">
		<fieldset class="control-group">
			<%= f.label :description, t("views.invoices._form.labels.description"), class: "control-label" %>
	    <div class="controls"><%= f.text_area :description, class: "span3", rows: 3 %></div>
		</fieldset>
	</div>

	<!-- Line Item Sub-Factors -->
	<div class="span4">
		<%= f.fields_for :sub_factors do |builder| %>
			<%= render "sub_factor_fields", :f => builder %>
		<% end %>
		<span class="buttons-and-links"><%= f.link_to_add t("views.invoices._form.links.add_a_sub_factor"), :sub_factors %></span>
	</div>
	<!-- /Line Item Sub-Factors -->

	<div class="span1">
		<fieldset class="control-group">
			<%= f.label :currency, t("views.invoices._form.labels.currency"), class: "control-label" %>
	    <div class="controls"><%= f.select :currency, Currency::CODES, { prompt: true }, { class: "span1" } %></div>
		</fieldset>
	</div>

	<div class="span1">
		<fieldset class="control-group">
			<%= f.label :unit_price, t("views.invoices._form.labels.unit_price"), class: "control-label" %>
	    <div class="controls"><%= f.text_field :unit_price, class: "span1" %></div>
		</fieldset>
	</div>

	<div class="span1">
		<fieldset class="control-group">
			<%= f.label :units, t("views.invoices._form.labels.action"), class: "control-label" %>
			<p><small><%= f.link_to_remove t("views.invoices._form.links.remove_this_line_item") %></small></p>
		</fieldset>
	</div>
</div>

app/views/invoices/_no_invoices.html.erb
<%= t("views.invoices._no_invoices.copy.no_invoices") %>

app/views/invoices/_sub_factor_fields.html.erb
<div class="row">
	<div class="span2">
		<fieldset class="control-group">
			<%= f.label :amount, t("views.invoices._form.labels.amount"), class: "control-label" %>
	    <div class="controls"><%= f.text_field :amount, class: "span1" %></div>
			<p><small><%= f.link_to_remove t('views.invoices._form.links.remove_this_sub_item') %></small></p>
		</fieldset>
	</div>

	<div class="span2">
		<fieldset class="control-group">
			<%= f.label :units, t("views.invoices._form.labels.units"), class: "control-label" %>
	    <div class="controls"><%= f.text_field :units, class: "span1" %></div>
		</fieldset>
	</div>
</div>

app/views/invoices/edit.html.erb
<% title t("views.invoices.edit.title", state: @invoice.state, number: @invoice.invoice_number) %>

<div class="page-header">
	<%= render "invoices/buttons_and_links", invoice: @invoice %>

	<h1><%= yield :title %></h1>
</div>

<%= render 'form' %>

app/views/invoices/new.html.erb
<% title t("views.invoices.new.title") %>

<div class="page-header">
	<h1><%= yield :title %></h1>
</div>

<%= render 'form' %>

app/views/invoices/paid.html.erb
<% title t("views.invoices.paid.title") %>

<div class="page-header">
	<div class="row">
		<div class="span9">
			<h1><%= yield :title %></h1>
		</div>
		<div class="span3 add">
			<%= link_to t("views.invoices.paid.buttons.add_an_invoice"), new_invoice_path, class:  "btn" %>
		</div>
	</div>
</div>

<%= render "invoices", invoices: @invoices %>

app/views/invoices/show.html.erb
<% title t("views.invoices.show.title", state: @invoice.state.titleize, number: @invoice.invoice_number) %>

<div id="invoice">
	<%= render "invoices/buttons_and_links", invoice: @invoice %>

	<div id="header">
		<h1>
			<%= t("views.invoices.show.copy.states.#{@invoice.state}") %>
			<%= @invoice.invoice_number %>
			<%= render "invoice_payment_status", invoice: @invoice %>
		</h1>
		<p><small><%= t("views.invoices.show.labels.uuid") %><%= t("views.application.copy.full_colon") %> <%= @invoice.uuid %></small></p>
	</div>

	<div id="addresses">
		<div class="row">
			<div class="span4">
				<h2>
					<small><%= t("views.invoices.show.labels.to") %></small><br />
					<%= @invoice.to %>
				</h2>

				<%=simple_format @invoice.to_address %>
			</div>

			<div class="span4 offset4">
				<h2>
					<small><%= t("views.invoices.show.labels.from") %></small><br />
					<%= @invoice.from %>
				</h2>

				<%=simple_format @invoice.from_address %>
			</div>
		</div>
	</div>
	
	<div id="dates">
		<h2><small><%= t("views.invoices.show.labels.dates") %></small></h2>
		<p>
			<strong><%= t("views.invoices.show.labels.invoiced_at") %></strong><%= t("views.application.copy.full_colon") %> <%= @invoice.invoiced_at.strftime("%A, %d %B %Y") %><br />
			<strong><%= t("views.invoices.show.labels.due_at") %></strong><%= t("views.application.copy.full_colon") %> <%= @invoice.due_at.strftime("%A, %d %B %Y") %><br />
			<!-- TODO: PAID AT --><br />
		</p>
	</div>

	<div id="description">
		<h2><small><%= t("views.invoices.show.labels.description") %></small></h2>
		<%=simple_format @invoice.description, class: "description" %>
	</div>

	<div id="line_items">
		<table class="table table-condensed table table-striped">
			<thead>
				<tr>
					<th class="quantity"><%= t("views.invoices.table.headings.quantity") %></th>
					<th class="description"><%= t("views.invoices.table.headings.description") %></th>
					<th class="sub_factor"><%= t("views.invoices.table.headings.sub_factors") %></th>
					<th class="cost"><%= t("views.invoices.table.headings.unit_price") %></th>
					<th class="total"><%= t("views.invoices.table.headings.total") %></th>
				</tr>
			</thead>
			<tbody>
			<% @invoice.line_item_units.each do |currency, line_items| %>
				<% currency_total = 0.0 %>
				<% for line_item in line_items do %>
					<% currency_total = currency_total + line_item.total %>
					<tr>
						<td class="quantity"><%= line_item.quantity %></td>
						<td class="description"><%=simple_format(line_item.description) %></td>
						<td class="sub_factor">
							<% line_item.sub_factors.each do |sub_factor| %>
								<%= sub_factor.amount %>
								<%= sub_factor.units %>
							<% end %>
						</td>
						<td class="cost"><%= t("models.currency.codes.#{line_item.currency}") %><%= number_to_currency(line_item.unit_price, :unit => "") %></td>
						<td class="total"><%= t("models.currency.codes.#{line_item.currency}") %><%= number_to_currency(line_item.total, :unit => "") %></td>
					</tr>
				<% end %>
				<tr class="currency_total">
					<td class="units" colspan="4"><strong><%= t("views.invoices.table.headings.total") %></strong></td>
					<td class="total"><strong><%= t("models.currency.codes.#{line_item.currency}") %><%= number_to_currency(currency_total, :unit => "") %></strong></td>
				</tr>
			<% end %>
			</tbody>
		</table>
		<!-- /Invoice Line Items -->
	</div>

	<% if @invoice.notes.present? %>
		<div id="notes">
			<div class="row">
				<span class="span8 offset4">
					<h2><small><%= t("views.invoices.show.labels.notes") %></small></h2>
					<%=simple_format @invoice.notes, class: "notes" %>
				</span>
			</div>
		</div>
	<% end %>

	<% if @invoice.terms.present? %>
		<div id="terms">
			<div class="row">
				<span class="span8 offset4">
					<h2><small><%= t("views.invoices.show.labels.terms") %></small></h2>
					<%=simple_format @invoice.terms, class: "terms" %>
				</span>
			</div>
		</div>
	<% end %>
</div>

app/views/invoices/unpaid.html.erb
<% title t("views.invoices.unpaid.title") %>

<div class="page-header">
	<div class="row">
		<div class="span9">
			<h1><%= yield :title %></h1>
		</div>
		<div class="span3 add">
			<%= link_to t("views.invoices.unpaid.buttons.add_an_invoice"), new_invoice_path, class:  "btn" %>
		</div>
	</div>
</div>

<%= render "invoices", invoices: @invoices %>