config/routes.rb
BillUp::Application.routes.draw do
  match "account_settings", to: "users#edit", as: "account_settings"
  match "exception_test", to: "welcome#exception_test", as: "exception_test"
  match "pricing", to: "welcome#pricing", as: "pricing"
  match "sign_in", to: "sessions#new", as: "sign_in"
  match "sign_out", to: "sessions#destroy", as: "sign_out"
  match "sign_up", to: "users#new", as: "sign_up"
  match "terms", to: "welcome#terms", as: "terms"
  match "tour", to: "welcome#tour", as: "tour"




  resources :organisations
  resources :sessions
  resources :users




  constraints subdomain: /.+/ do
    resources :clients
    resources :invoices do
      collection do
        get :paid
        get :unpaid
      end
    end
    resources :receipts
    root to: "organisations#show"
  end




  root to: "welcome#index"
end

app/models/client.rb
class Client < ActiveRecord::Base
  default_scope order("name")

  belongs_to :organisation

  validates :name, :presence => true, :uniqueness => { scope: [:organisation_id] }

  has_many :addresses, :as => :addressable, :dependent => :destroy
  has_many :invoices
  has_many :receipts

  accepts_nested_attributes_for :addresses, allow_destroy: true
  
  def random_address
    self.addresses[rand self.addresses.size]
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :sign_in_required
  before_filter :current_organisation
  before_filter :membership_required

  load_and_authorize_resource

  def index
    @clients = @current_organisation.clients
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client.addresses.build
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(params[:client])

    if @client.save
      flash[:success] = t("controllers.clients_controller.actions.create.success")
      redirect_to @client
    else
      render action: "new"
    end
  end

  def update
    @client = Client.find(params[:id])

    if @client.update_attributes(params[:client])
      flash[:notice] = t("controllers.clients_controller.actions.update.success")
      redirect_to @client
    else
      render action: "edit"
    end
  end

  #def destroy
  #  @client = @current_organisation.clients.find_by_id(params[:id])
  #  @client.destroy
  #
  #  redirect_to clients_url
  #end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_actions.html.erb
<div class="actions">
	<p>
		<small>
		<%= link_to_unless_current t("views.clients.clickables.links.cancel"), client %>
	</p>
</div>

app/views/clients/_actions_bar.html.erb
<div class="actions-bar well">
	<%= link_to t("views.clients.clickables.buttons.add_an_invoice"), new_invoice_path(client_id: client.id), class:  "btn small" %>
	<%= link_to t("views.clients.clickables.buttons.edit_this_client"), edit_client_path(client), class:  "btn small" %>
</div>

app/views/clients/_buttons_and_links.html.erb
<div class="buttons_and_links">
	<p>
		<small>
			<%= link_to_unless_current t("views.clients.clickables.links.cancel"), client %>
		</small>
	</p>
</div>

app/views/clients/_buttons_and_links_bar.html.erb
<div class="buttons_and_links_bar well">
	<%= link_to t("views.clients.clickables.buttons.add_an_invoice"), new_invoice_path(client_id: client.id), class:  "btn small" %>
	<%= link_to t("views.clients.clickables.buttons.add_a_receipt"), new_receipt_path(client_id: client.id), class:  "btn small" %>
	<%= link_to t("views.clients.clickables.buttons.edit_this_client"), edit_client_path(client), class:  "btn small" %>
</div>

app/views/clients/_clients.html.erb
<table class="table table-condensed table table-striped">
<% @clients.each do |client| %>
  <tr>
    <td><p><%= link_to client.name, client %></p></td>
  </tr>
<% end %>
</table>

<br />

app/views/clients/_errors.html.erb
<% if client.errors.any? %>
	<div id="error_explanation" class="alert-message block-message error">
	  <a class="close" data-dismiss="alert" href="#">&times;</a>

    <h2><%= t("views.clients._errors.title") %></h2>

    <ul>
    <% client.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/clients/_form.html.erb
<%= nested_form_for(@client) do |f| %>
	<fieldset class="control-group">

		<%= render "errors", client: @client %>

	   <%= f.hidden_field :organisation_id, value: @current_organisation.id %>

		<fieldset class="control-group">
			<div class="row">
				<div class="span8">
					<fieldset class="control-group">
						<legend><%= t("views.clients._form.legends.client") %></legend>
				    <%= f.label :name, t("views.clients._form.labels.name"), class: "control-label" %>
				    <div class="controls">
							<%= f.text_field :name, class: "span6" %>
							<p class="help-block"><%=raw t("views.clients._form.copy.hints.name") %></p>
						</div>
					</fieldset>
				</div>
				<div class="span4">
					<fieldset class="control-group">
						<legend><%= t("views.clients._form.legends.security") %></legend>
				    <%= f.label :pdf_password, t("views.clients._form.labels.pdf_password"), class: "control-label" %>
				    <div class="controls">
							<%= f.password_field :pdf_password, value: @client.pdf_password, class: "span3" %>
							<p class="help-block"><%=raw t("views.clients._form.copy.hints.pdf_password") %></p>
						</div>
				    <%= f.label :pdf_password_hint, t("views.clients._form.labels.pdf_password_hint"), class: "control-label" %>
				    <div class="controls">
							<%= f.text_field :pdf_password_hint, class: "span3" %>
							<p class="help-block"><%=raw t("views.clients._form.copy.hints.pdf_password_hint") %></p>
						</div>
					</fieldset>
				</div>
			</div>
		</fieldset>

		<!-- Address -->
		<fieldset class="control-group">
			<legend><%= t("views.addresses._form.legends.address") %></legend>
				<%= f.fields_for :addresses do |builder| %>
					<%= render "addresses/address_fields", f: builder %>
				<% end %>
			<p><small><%= f.link_to_add t("views.addresses._form.links.add_an_address"), :addresses %></small></p>
		</fieldset>
		<!-- Address -->

	  <div class="actions form-actions">
	    <%= f.submit class: "btn btn-large btn-primary" %>
	  </div>
	</fieldset>
<% end %>

app/views/clients/edit.html.erb
<% title t("views.clients.edit.title", client_name: @client.name) %>

<div class="page-header">
	<%= render "clients/buttons_and_links", client: @client %>

	<h1><%= yield :title %></h1>
	<!-- <p><%=raw t("views.clients.edit.hints.clients") %></p> -->
</div>

<%= render 'form' %>

app/views/clients/index.html.erb
<% title t("views.clients.index.title") %>

<div class="page-header">
	<div class="row">
		<div class="span10">
			<h1><%= yield :title %></h1>
		</div>
		<div class="span2 add">
			<%= link_to t("views.clients.index.buttons.add_a_client"), new_client_path, class:  "btn" %>
		</div>
	</div>
</div>

<div class="row">
	<div class="span9">
		<% if @clients.blank? %>
			<%= render "organisations/organisation_has_no_clients" %>
		<% else %>
			<%= render "clients" %>
		<% end %>
	</div>
	<div class="span3 sidebar">
		<div class="well">
			<ul class="nav nav-list">
				<li class="nav-header"><%= t("views.clients.show.headings.nav_list.client") %></li>
				<li><%= link_to t("views.clients.show.links.new_client"), new_client_path %></li>
			</ul>
		</div><!-- /.well -->
	</div>
</div>

app/views/clients/new.html.erb
<% title t("views.clients.new.title") %>

<div class="page-header">
	<h1><%= yield :title %></h1>

	<p class="hint"><%=raw t("views.clients.new.hints.clients") %></p>
</div>

<%= render "form" %>

app/views/clients/show.html.erb
<% title t("views.clients.show.title", client_name: @client.name) %>


<div class="page-header">
	<h1>
		<span class="client_name"><%= @client.name %></span><br />
		<small><%= t("views.clients.show.copy.client_of", organisation_name: @client.organisation.name ) %></small>
	</h1>
	<%= render "buttons_and_links_bar", client: @client %>
</div>

<div class="row">
	<div class="span9 content">
		<h2><%= t("views.clients.show.sub_titles.invoices") %></h2>
		<%= render "invoices/invoices", invoices: @client.invoices %>

		<br />

		<h2><%= t("views.clients.show.sub_titles.receipts") %></h2>
		<%= render "receipts/receipts", receipts: @client.receipts %>
	</div>
	<div class="span3 addresses">
		<h2><%= t("views.clients.show.sub_titles.addresses") %></h2>
		<%= render @client.addresses %>
	</div>
</div>