config/routes.rb
BillUp::Application.routes.draw do
  match "account_settings", to: "users#edit", as: "account_settings"
  match "exception_test", to: "welcome#exception_test", as: "exception_test"
  match "pricing", to: "welcome#pricing", as: "pricing"
  match "sign_in", to: "sessions#new", as: "sign_in"
  match "sign_out", to: "sessions#destroy", as: "sign_out"
  match "sign_up", to: "users#new", as: "sign_up"
  match "terms", to: "welcome#terms", as: "terms"
  match "tour", to: "welcome#tour", as: "tour"




  resources :organisations
  resources :sessions
  resources :users




  constraints subdomain: /.+/ do
    resources :clients
    resources :invoices do
      collection do
        get :paid
        get :unpaid
      end
    end
    resources :receipts
    root to: "organisations#show"
  end




  root to: "welcome#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  http_basic_authenticate_with name: AppConfig.http_basic_name, password: AppConfig.http_basic_password unless Rails.env == "test"

  check_authorization # CanCan Ref: https://github.com/ryanb/cancan/wiki/Ensure-Authorization

  helper_method :current_user, :user_signed_in?, :current_organisation

  before_filter :set_user_time_zone

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = t("controllers.application_controller.flash.access_denied")
    redirect_to root_path
  end

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end

  def membership_required
    if @current_organisation.members.exists?(id: current_user.id)
      # The current user can access this Organisation
      # Do nothing
    else
      # The current user is not allowed to access this Organisation
      flash[:error] = t("controllers.application_controller.flash.membership_required")
      redirect_to root_url(:host => request.domain)
    end
  end

  def sign_in_required
    unless current_user
      store_location
      flash[:notice] = t("controllers.application_controller.flash.sign_in_required")
      redirect_to sign_in_path
      return false
    end
  end

  def sign_out_required
    if current_user
      #store_location
      flash[:warning] = t("controllers.application_controller.flash.sign_out_required")
      redirect_to root_path
      return false
    end
  end

  def store_location
    session[:return_to] =
    if request.get?
      request.fullpath
    else
      request.referer
    end
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

  def set_user_time_zone
    Time.zone = current_user.time_zone if user_signed_in?
  end

  def current_organisation
    @current_organisation ||= Organisation.find_by_subdomain(request.subdomain) || resource_not_found
  end

  def resource_not_found
    raise ActionController::RoutingError.new("Not Found")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_id
    controller.controller_name
  end

  def index_action?
    (controller.action_name == "index")
  end

  def show_action?
    (controller.action_name == "show")
  end

  def new_or_create_action?
    (controller.action_name == "new") || (controller.action_name == "create")
  end

  def edit_or_update_action?
    (controller.action_name == "edit") || (controller.action_name == "update")
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def sub_title(sub_title)
    content_for(:sub_title) do
      content_tag :small do
        sub_title
      end
    end
  end
end

app/views/application/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21023959-1']);
  _gaq.push(['_setDomainName', '.billup.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/application/_clients_dropdown_navigation.html.erb
<ul class="nav">
	<li id="tab_clients_dropdown" class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			<%= t("views.application._navigation.links.clients") %>
			<b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<li id="tab_create_client"><%= link_to t("views.application._navigation.links.create_a_client"), new_client_path %></li>
			<li class="divider"></li>
			<li id="tab_clients"><%= link_to t("views.application._navigation.links.clients"), clients_path %></li>
		</ul>
	</li>
</ul>

app/views/application/_favicons.html.erb
<link rel="shortcut icon" href="<%= image_path("favicon.ico") %>" />
<link rel="apple-touch-icon" href="<%= image_path("apple-touch-icon.png") %>" />
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path("apple-touch-icon-72x72.png") %>" />
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path("apple-touch-icon-114x114.png") %>" />

app/views/application/_footer.html.erb
<footer>
	&copy; <%= Time.now.year %>
	<%= link_to t("application.name"), root_path %>.
</footer>

app/views/application/_invoices_dropdown_navigation.html.erb
<ul class="nav">
	<li id="tab_invoices_dropdown" class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t("views.application._navigation.links.invoices") %> <b class="caret"></b></a>
		<ul class="dropdown-menu">
			<li id="tab_create_invoice"><%= link_to t("views.application._navigation.links.create_an_invoice"), new_invoice_path %></li>
			<li class="divider"></li>
			<li id="tab_all_invoices"><%= link_to t("views.application._navigation.links.all_invoices"), invoices_path %></li>
			<li id="tab_paid_invoices"><%= link_to t("views.application._navigation.links.paid_invoices"), paid_invoices_path %></li>
			<li id="tab_unpaid_invoices"><%= link_to t("views.application._navigation.links.unpaid_invoices"), unpaid_invoices_path %></li>
		</ul>
	</li>
</ul>

app/views/application/_leaves_count.html.erb
<ul class="nav">
	<li id="tab_leaves_left" class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t("views.application._navigation.copy.leaves_left", leaves_left: @current_organisation.leaves_left) %> <b class="caret"></b></a>
		<ul class="dropdown-menu">
			<li id="tab_purchase_leaves"><%= link_to t("views.application._navigation.links.purchase_leaves"), new_invoice_path %></li>
		</ul>
	</li>
</ul>

app/views/application/_less_than_ie9.html.erb
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/application/_navigation.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<% if user_signed_in? %>
				<% if @current_organisation.present? %>
					<%= render "switch_to_dropdown_navigation" %>
					<%= link_to truncate(@current_organisation.name, :length => 30), root_path, class:  "brand" %>
					<%= render "invoices_dropdown_navigation" %>
					<%= render "receipts_dropdown_navigation" %>
					<%= render "clients_dropdown_navigation" %>
				<% end %>

				<ul class="nav pull-right">
					<%= render "user_dropdown_navigation" %>
				</ul>
			<% else %>
				<%= link_to t("application.name"), root_url(:host => request.domain), class:  "brand" %>
				<ul class="nav">
					<li id="tab_tour"><%= link_to t("views.application._navigation.links.tour"), tour_url(:host => request.domain) %></li>
					<li id="tab_pricing"><%= link_to t("views.application._navigation.links.pricing"), pricing_url(:host => request.domain) %></li>
					<li id="tab_sign_up"><%= link_to t("views.application._navigation.links.sign_up"), sign_up_url(:host => request.domain) %></li>
	      </ul><!-- /.nav -->

				<ul class="nav pull-right">
	        <li id="tab_sign_in"><%= link_to t("views.application._navigation.links.sign_in"), sign_in_path %></li>
				</ul>
			<% end %>
		</div><!-- /.container -->
	</div><!-- /.navbar-inner -->
</div><!-- /.navbar .navbar-fixed-top -->

app/views/application/_notifications.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
	  <%= content_tag :div, class:  "alert alert-#{name} fade in out", "data-alert" => "alert" do %>
			<a class="close" data-dismiss="alert" href="#">&times;</a>
			<%= msg %>
		<% end %>
	<% end %>
<% end %>

app/views/application/_switch_to_dropdown_navigation.html.erb
<ul class="nav">
	<li id="tab_organisations_dropdown" class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			<%= t("views.application._navigation.links.switch_to") %>
			<b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<li id="tab_create_organisation"><%= link_to t("views.application._navigation.links.create_an_organisation"), new_organisation_url(:host => request.domain) %></li>
			<li class="divider"></li>
			<% current_user.organisations.each do |organisation| %>
				<% if organisation == @current_organisation %>
					<%# Do nothing %>
				<% else %>
					<li id="tab_<%= organisation.subdomain %>"><%= link_to organisation.name, root_url(:subdomain => organisation.subdomain) %></li>
				<% end %>
			<% end %>
		</ul>
	</li>
</ul>

app/views/application/_tablesorter.html.erb
<script >
	$(function() {
		$("table#<%= table %>")
		.tablesorter({
			sortList: [[<%= column_number %>,1]]
		});
	});
</script>

app/views/application/_title.html.erb
<%= yield(:title).present? ? yield(:title) : t('application.tagline') %> // <%= t('application.name') %>

app/views/application/_units_dropdown_navigation.html.erb
<li id="tab_units_dropdown" class="dropdown">
	<a href="#" class="dropdown-toggle"  data-toggle="dropdown"><%= t("views.application._navigation.links.units_balance", :units => number_to_currency(current_user.units, :unit => "")) %> <b class="caret"></b></a>
	<ul class="dropdown-menu">
		<li><%= link_to t("views.application._navigation.links.purchase_units"), "purchase_units" %></li>
	</ul>
</li>

app/views/application/_user_dropdown_navigation.html.erb
<li id="tab_sign_out" class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown" alt="<%= current_user.name %>" title="<%= current_user.name %>">
		<i class="icon-user icon-white"></i>
		<b class="caret"></b>
	</a>
	<ul class="dropdown-menu">
		<li>
			<%= link_to root_url(:host => request.domain) do %>
				<i class="icon-home"></i>
				<%= current_user.name %>
			<% end %>
		</li>
		<li class="divider"></li>
		<li>
			<%= link_to account_settings_path do %>
				<i class="icon-cog"></i>
				<%= t("views.application._navigation.links.account_settings") %>
			<% end %>
		</li>
		<li class="divider"></li>
		<li>
			<%= link_to sign_out_path do %>
				<i class="icon-off"></i>
				<%= t("views.application._navigation.links.sign_out") %>
			<% end %>
		</li>
	</ul>
</li>