config/routes.rb
BillUp::Application.routes.draw do
  match "account_settings", to: "users#edit", as: "account_settings"
  match "exception_test", to: "welcome#exception_test", as: "exception_test"
  match "pricing", to: "welcome#pricing", as: "pricing"
  match "sign_in", to: "sessions#new", as: "sign_in"
  match "sign_out", to: "sessions#destroy", as: "sign_out"
  match "sign_up", to: "users#new", as: "sign_up"
  match "terms", to: "welcome#terms", as: "terms"
  match "tour", to: "welcome#tour", as: "tour"




  resources :organisations
  resources :sessions
  resources :users




  constraints subdomain: /.+/ do
    resources :clients
    resources :invoices do
      collection do
        get :paid
        get :unpaid
      end
    end
    resources :receipts
    root to: "organisations#show"
  end




  root to: "welcome#index"
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  default_scope order("receipt_number DESC")

  has_paper_trail

  belongs_to :client
  belongs_to :reconciliation
  belongs_to :organisation

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :currency, presence: true
  validates :from, presence: { if: :without_from_address_id? }
  validates :from_address, presence: { if: :without_from_address_id? }
  validates :payment_method, presence: true
  validates :receipt_number, presence: true, numericality: true, uniqueness: { scope: [:organisation_id] }
  validates :received_at, presence: true
  validates :to, presence: { if: :without_to_address_id? }
  validates :to_address, presence: { if: :without_to_address_id? }
  validates :uuid, presence: true, uniqueness: true

  validates :from_address_id, presence: { if: :without_from_fields? }, on: :create
  validates :to_address_id, presence: { if: :without_to_fields? }, on: :create

  attr_accessor :from_address_id
  attr_accessor :to_address_id

  before_create :fill_in_addresses

  def file_name
    "#{I18n.t("views.receipts.copy.receipt")} #{self.receipt_number} #{I18n.t("views.receipts.show.labels.from")} #{self.client.name}.pdf"
  end

private

  def fill_in_addresses
    to_address = Address.find_by_id(self.to_address_id)
    from_address = Address.find_by_id(self.from_address_id)

    self.from = from_address.addressable.name
    self.from_address = from_address.formatted_address

    self.to = to_address.addressable.name
    self.to_address = to_address.formatted_address
  end

  def without_from_address_id?
    self.from_address_id.blank?
  end

  def without_to_address_id?
    self.to_address_id.blank?
  end
  
  def without_from_fields?
    self.from_address.blank? || self.from.blank?
  end

  def without_to_fields?
    self.to_address.blank? || self.to.blank?
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_filter :sign_in_required
  before_filter :current_organisation
  before_filter :membership_required

  load_and_authorize_resource

  def index
    @receipts = @current_organisation.receipts
  end

  def show
    @receipt = @current_organisation.receipts.find_by_id(params[:id])
  end

  def new
    @client = @current_organisation.clients.find_by_id(params[:client_id]) if params[:client_id]
    if @client.present?
      @client_addresses = @client.addresses
    else
      # Finds all addresses associated to all the clients of this organisation:
      # Ref: http://stackoverflow.com/questions/7211846/rails-nested-has-many-association-finding-all-children
      @client_addresses = @current_organisation.clients.map(&:addresses).flatten
    end

    @receipt = Receipt.new
    @receipt.uuid = SecureRandom.uuid
    
    if @current_organisation.receipts.blank?
      @receipt.receipt_number = 1
    else
      @receipt.receipt_number = @current_organisation.receipts.first.receipt_number + 1
    end
  end

  def create
    @receipt = Receipt.new(params[:receipt])
    @receipt.organisation = @current_organisation
    @receipt.client = Address.find_by_id(params[:receipt][:from_address_id]).addressable if params[:receipt][:from_address_id].present?

    if @receipt.save
      flash[:success] = t("controllers.receipts_controller.actions.create.success")
      redirect_to @receipt
    else
      # Reset @client_addresses so that validation errors can be presented correctly
      if @client.present?
        @client_addresses = @client.addresses
      else
        # Finds all addresses associated to all the clients of this organisation:
        # Ref: http://stackoverflow.com/questions/7211846/rails-nested-has-many-association-finding-all-children
        @client_addresses = @current_organisation.clients.map(&:addresses).flatten
      end
      render action: "new"
    end
  end

  def edit
    @receipt = @current_organisation.receipts.find_by_id(params[:id])
  end

  def update
    @receipt = @current_organisation.receipts.find_by_id(params[:id])

    if @receipt.update_attributes(params[:receipt])
      flash[:success] = t('controllers.receipts_controller.actions.update.success')
      redirect_to @receipt
    else
      render action: "edit"
    end
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_actions.html.erb
<% if !edit_or_update_action? %>
	<div class="actions">
		<p>
			<small>
			<%= link_to_unless_current t('views.receipts._actions.links.view'), receipt_path(receipt) %>
			| <%= link_to_unless_current t('views.receipts._actions.links.pdf'), receipt_path(receipt, :format => 'pdf') %>
			| <%= link_to_unless_current t('views.receipts._actions.links.edit'), edit_receipt_path(receipt) %>
			</small>
		</p>
	</div>
<% else %>
	<div class="actions">
		<p>
			<small>
			<%= link_to_unless_current t("views.receipts.clickables.links.cancel"), receipt %>
		</p>
	</div>
<% end %>

app/views/receipts/_buttons_and_links.html.erb
<% if index_action? %>
	<div class="buttons_and_links">
		<p>
			<small>
				<%= link_to_unless_current t("views.receipts.clickables.links.view"), receipt %>
				| <%= link_to_unless_current t('views.receipts.clickables.links.edit'), edit_receipt_path(receipt) %>
				| <%= link_to_unless_current t('views.receipts.clickables.links.pdf'), receipt_path(receipt, :format => 'pdf') %>
			</small>
		</p>
	</div>
<% elsif (show_action? || edit_or_update_action?) %>
	<div class="buttons_and_links">
		<p>
			<small>
			<%= link_to_unless_current t("views.receipts.clickables.links.view"), receipt %>
			| <%= link_to_unless_current t('views.receipts.clickables.links.edit'), edit_receipt_path(receipt) %>
			| <%= link_to_unless_current t("views.receipts.clickables.links.new"), new_receipt_path(client_id: receipt.client.id) %>
			| <%= link_to_unless_current t('views.receipts.clickables.links.pdf'), receipt_path(receipt, :format => 'pdf') %>
			| <%= link_to_unless_current t("views.receipts.clickables.links.client"), client_path(receipt.client, anchor: "receipts") %>
			</small>
		</p>
	</div>
<% end %>

app/views/receipts/_errors.html.erb
<% if receipt.errors.any? %>
	<div id="error_explanation" class="alert-message fade in out block-message error">
	  <a class="close" data-dismiss="alert" href="#">&times;</a>

	  <h2><%= t("views.receipts._errors.title") %></h2>

    <ul>
    <% receipt.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/receipts/_form.html.erb
<%= nested_form_for(@receipt) do |f| %>
	<fieldset class="control-group">

		<%= render "errors", receipt: @receipt %>

		<div class="row">
			<div class="span4">
				<fieldset class="control-group">
					<legend><%= t("views.receipts._form.legends.receipt_number") %></legend>
					<%= f.label :receipt_number, t("views.receipts._form.labels.receipt_number") %>
			    <div class="controls"><%= f.text_field :receipt_number, class: "span3" %></div>
				</fieldset>
			</div>
			<div class="span4">
				<fieldset class="control-group">
					<legend><%= t("views.receipts._form.legends.uuid") %></legend>
					<%= f.label :uuid, t("views.receipts._form.labels.uuid") %>
			    <div class="controls"><%= f.text_field :uuid, class: "span3" %></div>
				</fieldset>
			</div>
		</div>

		<% if new_or_create_action? %>
			<%= render 'form_fields_for_new', { receipt: @receipt, client_addresses: @client_addresses, client: @client , current_organisation: @current_organisation, f: f } %>
		<% else %>
			<%= render 'form_fields_for_edit', { receipt: @receipt, f: f } %>
		<% end %>

		<fieldset>
			<legend><%= t("views.receipts._form.legends.details") %></legend>
			<div class="row">
				<div class="span6">
					<fieldset class="control-group">
						<%= f.label :description, t("views.receipts._form.labels.description") %>
				    <div class="controls"><%= f.text_area :description, class: "span5", rows: 10 %></div>
					</fieldset>
				</div>

				<div class="span6">
					<div class="row">
						<div class="span3">
							<fieldset class="control-group">
								<%= f.label :amount, t("views.receipts._form.labels.amount"), class: "control-label" %>
						    <div class="controls"><%= f.text_field :amount, class: "span2" %></div>
							</fieldset>
						</div>
						<div class="span3">
							<fieldset class="control-group">
								<%= f.label :currency, t("views.receipts._form.labels.currency"), class: "control-label" %>
						    <div class="controls"><%= f.select :currency, Currency::CODES, { prompt: true }, { class: "span2" } %></div>
							</fieldset>
						</div>				
					</div>				
					<fieldset class="control-group">
						<%= f.label :payment_method, t("views.receipts._form.labels.payment_method"), class: "control-label" %>
				    <div class="controls"><%= f.select :payment_method, Payment::METHODS, { prompt: true } %></div>
					</fieldset>
					<fieldset class="control-group">
						<%= f.label :received_at, t("views.receipts._form.labels.received_at") %>
				    <div class="controls"><%= f.date_select :received_at, {}, class: "span2" %></div>
					</fieldset>
				</div>
			</div>
		</fieldset>

		<fieldset class="control-group">
			<legend><%= t("views.receipts._form.legends.notes") %></legend>
			<%= f.label :notes, t("views.receipts._form.labels.notes") %>
	    <div class="controls"><%= f.text_area :notes, class: "span5", rows: 3 %></div>
		</fieldset>

	  <div class="actions form-actions">
	    <%= f.submit class: "btn btn-large btn-primary" %>
	  </div>
	</fieldset>
<% end %>

app/views/receipts/_form_fields_for_edit.html.erb
<div class="row">
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.receipts._form.legends.from") %></legend>

			<fieldset class="control-group">
				<%= f.label :from, t("views.receipts._form.labels.from") %>
		    <div class="controls"><%= f.text_field :from, class: "span3" %></div>
			</fieldset>

			<fieldset class="control-group">
				<%= f.label :from_address, raw(t("views.receipts._form.labels.from_address")) %>
		    <div class="controls"><%= f.text_area :from_address, class: "span5", rows: 7 %></div>
			</fieldset>
		</fieldset>
	</div>
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.receipts._form.legends.to") %></legend>

			<fieldset class="control-group">
				<%= f.label :to, t("views.receipts._form.labels.to") %>
		    <div class="controls"><%= f.text_field :to, class: "span3" %></div>
			</fieldset>

			<fieldset class="control-group">
				<%= f.label :to_address, raw(t("views.receipts._form.labels.to_address")) %>
		    <div class="controls"><%= f.text_area :to_address, class: "span5", rows: 7 %></div>
			</fieldset>
		</fieldset>
	</div>
</div>

app/views/receipts/_form_fields_for_new.html.erb
<div class="row">
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.receipts._form.legends.from") %></legend>
			<%= f.label :from_address_id, t("views.receipts._form.labels.from") %>
			<div class="controls">
				<%= f.collection_select(:from_address_id, client_addresses, :id, :summary, { prompt: true }, { class: "span5" }) %>
				<% if client.present? %>
					<p class="help-block">
						<%=raw t("views.receipts._form.copy.hints.from_address_id", client_name: client.name) %>
						<small>
							<%= link_to t("views.receipts.clickables.links.all_clients"), new_receipt_path %><%= t("views.application.copy.full_stop") %>
						</small>
					</p>
				<% end %>
			</div>
		</fieldset>
	</div>
	<div class="span6">
		<fieldset class="control-group">
			<legend><%= t("views.receipts._form.legends.to") %></legend>
			<%= f.label :to_address_id, t("views.receipts._form.labels.to") %>
			<div class="controls">
				<%= f.collection_select(:to_address_id, current_organisation.addresses, :id, :summary, {}, { class: "span5" }) %>
			</div>
		</fieldset>
	</div>
</div>

app/views/receipts/_no_receipts.html.erb
<%= t("views.receipts.copy.no_receipts") %>

app/views/receipts/_receipts.html.erb
<% if receipts.present? %>
<%= render "tablesorter", { table: "table_of_receipts", column_number: 3 } %>
	<div id="receipts_table">
		<table id="table_of_receipts" class="table table-condensed table table-striped">
		  <thead>
				<tr>
				  <th class="receipt_number"><%= t("views.receipts.table.headings.receipt_number") %></th>
				  <th class="to"><%= t("views.receipts.table.headings.from") %></th>
				  <th class="amount"><%= t("views.receipts.table.headings.amount") %></th>
				  <th class="received_at"><%= t("views.receipts.table.headings.received_at") %></th>
					<th class="buttons_and_links"><%= t("views.receipts.table.headings.actions") %></th>
				</tr>
			</thead>
		  <tbody>
				<% receipts.each do |receipt| %>
			  <tr class="receipt">
			    <td class="receipt_number">
						<%= link_to_unless_current receipt.receipt_number, receipt, { rel: "tooltip", title: "#{receipt.client.name}#{t("views.application.copy.full_colon")} #{receipt.description}" } %>
					</td>
			    <td class="from"><%= link_to_unless_current receipt.from, receipt.client %></td>
			    <td class="amount"><%= t("models.currency.codes.#{receipt.currency}") %><%= number_to_currency(receipt.amount, :unit => "") %></td>
			    <td class="received_at" title="<%= receipt.received_at.strftime("%A, %d %B %Y") %>">
						<%= receipt.received_at.strftime("%Y-%m-%d") %>
					</td>
			    <td class="buttons_and_links">
						<%= render "receipts/buttons_and_links", receipt: receipt %>
					</td>
			  </tr>
				<% end %>
			</tbody>
		</table>
	</div><!-- /#receipts_table -->
<% else %>
	<%= render "receipts/no_receipts"%>
<% end %>

app/views/receipts/edit.html.erb
<% title t("views.receipts.edit.title", number: @receipt.receipt_number) %>

<div class="page-header">
	<%= render "receipts/buttons_and_links", receipt: @receipt %>
	<h1><%= yield :title %></h1>
</div>

<%= render 'form' %>

app/views/receipts/index.html.erb
<% title t("views.receipts.index.title") %>

<div class="page-header">
	<div class="row">
		<div class="span9">
			<h1><%= yield :title %></h1>
		</div>
		<div class="span3 add">
			<%= link_to t("views.receipts.clickables.buttons.add_a_receipt"), new_receipt_path, class:  "btn" %>
		</div>
	</div>
</div>

<%= render "receipts", receipts: @receipts %>

app/views/receipts/new.html.erb
<% title t("views.receipts.new.title") %>

<div class="page-header">
	<h1><%= yield :title %></h1>
</div>

<%= render 'form' %>

app/views/receipts/show.html.erb
<% title t("views.receipts.show.title", number: @receipt.receipt_number) %>

<div id="receipt">
	<div id="header">
		<div class="row">
			<div class="span10 headings">
				<h1>
					<%= t("views.receipts.show.copy.receipt") %>
					<%= @receipt.receipt_number %><br />
				</h1>
				<p><small><%= t("views.receipts.show.labels.uuid") %><%= t("views.application.copy.full_colon") %> <%= @receipt.uuid %></small></p>
			</div>
			<%= render "receipts/buttons_and_links", receipt: @receipt %>
		</div>

	<div id="addresses">
		<div class="row">
			<div class="span4">
				<h2>
					<small><%= t("views.receipts.show.labels.from") %></small><br />
					<%= @receipt.from %>
				</h2>

				<%=simple_format @receipt.from_address %>
			</div>

			<div class="span4 offset4">
				<h2>
					<small><%= t("views.receipts.show.labels.to") %></small><br />
					<%= @receipt.to %>
				</h2>

				<%=simple_format @receipt.to_address %>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div id="description" class="span8">
			<p class="description">
				<%=raw t("views.receipts.show.copy.acknowledgement",
				organisation: @receipt.organisation.name,
				amount: "#{t("models.currency.codes.#{@receipt.currency}")}#{number_to_currency(@receipt.amount, unit: "")}",
				payment_method: t("views.receipts.show.copy.payment_method.#{@receipt.payment_method}"),
				client: @receipt.client.name,
				payment_date: @receipt.received_at.strftime("%A, %d %B %Y"),
				)
				%>
			</p>

			<h2><small><%= t("views.receipts.show.labels.description") %></small></h2>
			<%=simple_format @receipt.description, class: "description" %>
	
			<br />

			<h3 class="total_received">
				<%= t("views.receipts.show.copy.total_received", amount: "#{t("models.currency.codes.#{@receipt.currency}")}#{number_to_currency(@receipt.amount, unit: "")}") %>
			</h3>
	
		</div>
	</div>

	<% if @receipt.notes.present? %>
		<div id="notes">
			<div class="row">
				<span class="span8">
					<h2><small><%= t("views.receipts.show.labels.notes") %></small></h2>
					<%=simple_format @receipt.notes, class: "notes" %>
				</span>
			</div>
		</div>
	<% end %>
</div>